spring:
  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: none # none, validate, create, create-drop, update
    database-platform: org.hibernate.dialect.MySQLDialect
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/spring_demo?useUnicode=true&characterEncoding=utf-8&useSSL=false&rewriteBatchedStatements=true&serverTimezone=Asia/Shanghai
    type: org.apache.tomcat.jdbc.pool.DataSource
    tomcat:
      initial-size: 10
      max-active: 100
      max-wait: 10000
      test-while-idle: true
      test-on-borrow: true
      validation-query: SELECT 1
      validation-interval: 3000
      time-between-eviction-runs-millis: 30000
      log-abandoned: true
  flyway:
    enabled: false
    validate-migration-naming: false